<?php

namespace Database\Seeders;

use App\Models\Country;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class CountrySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    // public function run(): void
    // {
    //     Country::insert([
    //             ['country' => 'Afghanistan', 'country_code' => 'AF', 'phone_code' => 'Afghanistan AF +93'],
    //             ['country' => 'Albania', 'country_code' => 'AL', 'phone_code' => 'Albania AL +355'],
    //             ['country' => 'Algeria', 'country_code' => 'DZ', 'phone_code' => 'Algeria DZ +213'],
    //             ['country' => 'Andorra', 'country_code' => 'AD', 'phone_code' => 'Andorra AD +376'],
    //             ['country' => 'Angola', 'country_code' => 'AO', 'phone_code' => 'Angola AO +244'],
    //             ['country' => 'Argentina', 'country_code' => 'AR', 'phone_code' => 'Argentina AR +54'],
    //             ['country' => 'Armenia', 'country_code' => 'AM', 'phone_code' => 'Armenia AM +374'],
    //             ['country' => 'Australia', 'country_code' => 'AU', 'phone_code' => 'Australia AU +61'],
    //             ['country' => 'Austria', 'country_code' => 'AT', 'phone_code' => 'Austria AT +43'],
    //             ['country' => 'Azerbaijan', 'country_code' => 'AZ', 'phone_code' => 'Azerbaijan AZ +994'],
    //             ['country' => 'Bahamas', 'country_code' => 'BS', 'phone_code' => 'Bahamas BS +1-242'],
    //             ['country' => 'Bahrain', 'country_code' => 'BH', 'phone_code' => 'Bahrain BH +973'],
    //             ['country' => 'Bangladesh', 'country_code' => 'BD', 'phone_code' => 'Bangladesh BD +880'],
    //             ['country' => 'Barbados', 'country_code' => 'BB', 'phone_code' => 'Barbados BB +1-246'],
    //             ['country' => 'Belarus', 'country_code' => 'BY', 'phone_code' => 'Belarus BY +375'],
    //             ['country' => 'Belgium', 'country_code' => 'BE', 'phone_code' => 'Belgium BE +32'],
    //             ['country' => 'Belize', 'country_code' => 'BZ', 'phone_code' => 'Belize BZ +501'],
    //             ['country' => 'Benin', 'country_code' => 'BJ', 'phone_code' => 'Benin BJ +229'],
    //             ['country' => 'Bhutan', 'country_code' => 'BT', 'phone_code' => 'Bhutan BT +975'],
    //             ['country' => 'Bolivia', 'country_code' => 'BO', 'phone_code' => 'Bolivia BO +591'],
                // ['country' => 'Bosnia and Herzegovina', 'country_code' => 'BA', 'phone_code' => 'Bosnia and Herzegovina BA +387'],
                // ['country' => 'Botswana', 'country_code' => 'BW', 'phone_code' => 'Botswana BW +267'],
                // ['country' => 'Brazil', 'country_code' => 'BR', 'phone_code' => 'Brazil BR +55'],
                // ['country' => 'Brunei', 'country_code' => 'BN', 'phone_code' => 'Brunei BN +673'],
                // ['country' => 'Bulgaria', 'country_code' => 'BG', 'phone_code' => 'Bulgaria BG +359'],
                // ['country' => 'Burkina Faso', 'country_code' => 'BF', 'phone_code' => 'Burkina Faso BF +226'],
                // ['country' => 'Burundi', 'country_code' => 'BI', 'phone_code' => 'Burundi BI +257'],
                // ['country' => 'Cambodia', 'country_code' => 'KH', 'phone_code' => 'Cambodia KH +855'],
                // ['country' => 'Cameroon', 'country_code' => 'CM', 'phone_code' => 'Cameroon CM +237'],
                // ['country' => 'Canada', 'country_code' => 'CA', 'phone_code' => 'Canada CA +1'],
                // ['country' => 'Cape Verde', 'country_code' => 'CV', 'phone_code' => 'Cape Verde CV +238'],
                // ['country' => 'Chile', 'country_code' => 'CL', 'phone_code' => 'Chile CL +56'],
                // ['country' => 'China', 'country_code' => 'CN', 'phone_code' => 'China CN +86'],
                // ['country' => 'Colombia', 'country_code' => 'CO', 'phone_code' => 'Colombia CO +57'],
                // ['country' => 'Costa Rica', 'country_code' => 'CR', 'phone_code' => 'Costa Rica CR +506'],
                // ['country' => 'Croatia', 'country_code' => 'HR', 'phone_code' => 'Croatia HR +385'],
                // ['country' => 'Cuba', 'country_code' => 'CU', 'phone_code' => 'Cuba CU +53'],
                // ['country' => 'Cyprus', 'country_code' => 'CY', 'phone_code' => 'Cyprus CY +357'],
                // ['country' => 'Czech Republic', 'country_code' => 'CZ', 'phone_code' => 'Czech Republic CZ +420'],
                // ['country' => 'Denmark', 'country_code' => 'DK', 'phone_code' => 'Denmark DK +45'],
                // ['country' => 'Dominican Republic', 'country_code' => 'DO', 'phone_code' => 'Dominican Republic DO +1-809'],
                // ['country' => 'Ecuador', 'country_code' => 'EC', 'phone_code' => 'Ecuador EC +593'],
                // ['country' => 'Egypt', 'country_code' => 'EG', 'phone_code' => 'Egypt EG +20'],
                // ['country' => 'El Salvador', 'country_code' => 'SV', 'phone_code' => 'El Salvador SV +503'],
                // ['country' => 'Estonia', 'country_code' => 'EE', 'phone_code' => 'Estonia EE +372'],
                // ['country' => 'Ethiopia', 'country_code' => 'ET', 'phone_code' => 'Ethiopia ET +251'],
                // ['country' => 'Fiji', 'country_code' => 'FJ', 'phone_code' => 'Fiji FJ +679'],
                // ['country' => 'Finland', 'country_code' => 'FI', 'phone_code' => 'Finland FI +358'],
                // ['country' => 'France', 'country_code' => 'FR', 'phone_code' => 'France FR +33'],
                // ['country' => 'Georgia', 'country_code' => 'GE', 'phone_code' => 'Georgia GE +995'],
                // ['country' => 'Germany', 'country_code' => 'DE', 'phone_code' => 'Germany DE +49'],
                // ['country' => 'Ghana', 'country_code' => 'GH', 'phone_code' => 'Ghana GH +233'],
                // ['country' => 'Greece', 'country_code' => 'GR', 'phone_code' => 'Greece GR +30'],
                // ['country' => 'Guatemala', 'country_code' => 'GT', 'phone_code' => 'Guatemala GT +502'],
                // ['country' => 'Honduras', 'country_code' => 'HN', 'phone_code' => 'Honduras HN +504'],
                // ['country' => 'Hong Kong', 'country_code' => 'HK', 'phone_code' => 'Hong Kong HK +852'],
                // ['country' => 'Hungary', 'country_code' => 'HU', 'phone_code' => 'Hungary HU +36'],
                // ['country' => 'Iceland', 'country_code' => 'IS', 'phone_code' => 'Iceland IS +354'],
                // ['country' => 'India', 'country_code' => 'IN', 'phone_code' => 'India IN +91'],
                // ['country' => 'Indonesia', 'country_code' => 'ID', 'phone_code' => 'Indonesia ID +62'],
                // ['country' => 'Iran', 'country_code' => 'IR', 'phone_code' => 'Iran IR +98'],
                // ['country' => 'Iraq', 'country_code' => 'IQ', 'phone_code' => 'Iraq IQ +964'],
                // ['country' => 'Ireland', 'country_code' => 'IE', 'phone_code' => 'Ireland IE +353'],
                // ['country' => 'Israel', 'country_code' => 'IL', 'phone_code' => 'Israel IL +972'],
                // ['country' => 'Italy', 'country_code' => 'IT', 'phone_code' => 'Italy IT +39'],
                // ['country' => 'Jamaica', 'country_code' => 'JM', 'phone_code' => 'Jamaica JM +1-876'],
                // ['country' => 'Japan', 'country_code' => 'JP', 'phone_code' => 'Japan JP +81'],
                // ['country' => 'Jordan', 'country_code' => 'JO', 'phone_code' => 'Jordan JO +962'],
                // ['country' => 'Kazakhstan', 'country_code' => 'KZ', 'phone_code' => 'Kazakhstan KZ +7'],
                // ['country' => 'Kenya', 'country_code' => 'KE', 'phone_code' => 'Kenya KE +254'],
                // ['country' => 'Kuwait', 'country_code' => 'KW', 'phone_code' => 'Kuwait KW +965'],
                // ['country' => 'Latvia', 'country_code' => 'LV', 'phone_code' => 'Latvia LV +371'],
                // ['country' => 'Lebanon', 'country_code' => 'LB', 'phone_code' => 'Lebanon LB +961'],
                // ['country' => 'Libya', 'country_code' => 'LY', 'phone_code' => 'Libya LY +218'],
                // ['country' => 'Lithuania', 'country_code' => 'LT', 'phone_code' => 'Lithuania LT +370'],
                // ['country' => 'Luxembourg', 'country_code' => 'LU', 'phone_code' => 'Luxembourg LU +352'],
                // ['country' => 'Malaysia', 'country_code' => 'MY', 'phone_code' => 'Malaysia MY +60'],
                // ['country' => 'Maldives', 'country_code' => 'MV', 'phone_code' => 'Maldives MV +960'],
                // ['country' => 'Mali', 'country_code' => 'ML', 'phone_code' => 'Mali ML +223'],
                // ['country' => 'Malta', 'country_code' => 'MT', 'phone_code' => 'Malta MT +356'],
                // ['country' => 'Mauritius', 'country_code' => 'MU', 'phone_code' => 'Mauritius MU +230'],
                // ['country' => 'Mexico', 'country_code' => 'MX', 'phone_code' => 'Mexico MX +52'],
                // ['country' => 'Morocco', 'country_code' => 'MA', 'phone_code' => 'Morocco MA +212'],
                // ['country' => 'Nepal', 'country_code' => 'NP', 'phone_code' => 'Nepal NP +977'],
                // ['country' => 'Netherlands', 'country_code' => 'NL', 'phone_code' => 'Netherlands NL +31'],
                // ['country' => 'New Zealand', 'country_code' => 'NZ', 'phone_code' => 'New Zealand NZ +64'],
                // ['country' => 'Nigeria', 'country_code' => 'NG', 'phone_code' => 'Nigeria NG +234'],
                // ['country' => 'Norway', 'country_code' => 'NO', 'phone_code' => 'Norway NO +47'],
                // ['country' => 'Pakistan', 'country_code' => 'PK', 'phone_code' => 'Pakistan PK +92'],
                // ['country' => 'Panama', 'country_code' => 'PA', 'phone_code' => 'Panama PA +507'],
                // ['country' => 'Peru', 'country_code' => 'PE', 'phone_code' => 'Peru PE +51'],
                // ['country' => 'Philippines', 'country_code' => 'PH', 'phone_code' => 'Philippines PH +63'],
                // ['country' => 'Poland', 'country_code' => 'PL', 'phone_code' => 'Poland PL +48'],
                // ['country' => 'Portugal', 'country_code' => 'PT', 'phone_code' => 'Portugal PT +351'],
                // ['country' => 'Qatar', 'country_code' => 'QA', 'phone_code' => 'Qatar QA +974'],
                // ['country' => 'Romania', 'country_code' => 'RO', 'phone_code' => 'Romania RO +40'],
                // ['country' => 'Russia', 'country_code' => 'RU', 'phone_code' => 'Russia RU +7'],
                // ['country' => 'Rwanda', 'country_code' => 'RW', 'phone_code' => 'Rwanda RW +250'],
                // ['country' => 'Saudi Arabia', 'country_code' => 'SA', 'phone_code' => 'Saudi Arabia SA +966'],
                // ['country' => 'Singapore', 'country_code' => 'SG', 'phone_code' => 'Singapore SG +65'],
                // ['country' => 'South Africa', 'country_code' => 'ZA', 'phone_code' => 'South Africa ZA +27'],
                // ['country' => 'South Korea', 'country_code' => 'KR', 'phone_code' => 'South Korea KR +82'],
                // ['country' => 'Spain', 'country_code' => 'ES', 'phone_code' => 'Spain ES +34'],
                // ['country' => 'Sri Lanka', 'country_code' => 'LK', 'phone_code' => 'Sri Lanka LK +94'],
                // ['country' => 'Sweden', 'country_code' => 'SE', 'phone_code' => 'Sweden SE +46'],
                // ['country' => 'Switzerland', 'country_code' => 'CH', 'phone_code' => 'Switzerland CH +41'],
                // ['country' => 'Thailand', 'country_code' => 'TH', 'phone_code' => 'Thailand TH +66'],
                // ['country' => 'Turkey', 'country_code' => 'TR', 'phone_code' => 'Turkey TR +90'],
                // ['country' => 'Uganda', 'country_code' => 'UG', 'phone_code' => 'Uganda UG +256'],
                // ['country' => 'Ukraine', 'country_code' => 'UA', 'phone_code' => 'Ukraine UA +380'],
                // ['country' => 'United Arab Emirates', 'country_code' => 'AE', 'phone_code' => 'United Arab Emirates AE +971'],
                // ['country' => 'United Kingdom', 'country_code' => 'GB', 'phone_code' => 'United Kingdom GB +44'],
                // ['country' => 'United States', 'country_code' => 'US', 'phone_code' => 'United States US +1'],
                // ['country' => 'Uruguay', 'country_code' => 'UY', 'phone_code' => 'Uruguay UY +598'],
                // ['country' => 'Venezuela', 'country_code' => 'VE', 'phone_code' => 'Venezuela VE +58'],
                // ['country' => 'Vietnam', 'country_code' => 'VN', 'phone_code' => 'Vietnam VN +84'],
                // ['country' => 'Yemen', 'country_code' => 'YE', 'phone_code' => 'Yemen YE +967'],
                // ['country' => 'Zimbabwe', 'country_code' => 'ZW', 'phone_code' => 'Zimbabwe ZW +263'],
            
    //     ]);
    // }

    public function run(): void
{
    Country::insert([
        ['country' => 'Afghanistan', 'country_code' => 'AF', 'phone_code' => 'Afghanistan AF +93'],
        ['country' => 'Albania', 'country_code' => 'AL', 'phone_code' => 'Albania AL +355'],
        ['country' => 'Algeria', 'country_code' => 'DZ', 'phone_code' => 'Algeria DZ +213'],
        ['country' => 'Andorra', 'country_code' => 'AD', 'phone_code' => 'Andorra AD +376'],
        ['country' => 'Angola', 'country_code' => 'AO', 'phone_code' => 'Angola AO +244'],
        ['country' => 'Argentina', 'country_code' => 'AR', 'phone_code' => 'Argentina AR +54'],
        ['country' => 'Armenia', 'country_code' => 'AM', 'phone_code' => 'Armenia AM +374'],
        ['country' => 'Australia', 'country_code' => 'AU', 'phone_code' => 'Australia AU +61'],
        ['country' => 'Austria', 'country_code' => 'AT', 'phone_code' => 'Austria AT +43'],
        ['country' => 'Azerbaijan', 'country_code' => 'AZ', 'phone_code' => 'Azerbaijan AZ +994'],
        ['country' => 'Bahamas', 'country_code' => 'BS', 'phone_code' => 'Bahamas BS +1-242'],
        ['country' => 'Bahrain', 'country_code' => 'BH', 'phone_code' => 'Bahrain BH +973'],
        ['country' => 'Bangladesh', 'country_code' => 'BD', 'phone_code' => 'Bangladesh BD +880'],
        ['country' => 'Barbados', 'country_code' => 'BB', 'phone_code' => 'Barbados BB +1-246'],
        ['country' => 'Belarus', 'country_code' => 'BY', 'phone_code' => 'Belarus BY +375'],
        ['country' => 'Belgium', 'country_code' => 'BE', 'phone_code' => 'Belgium BE +32'],
        ['country' => 'Belize', 'country_code' => 'BZ', 'phone_code' => 'Belize BZ +501'],
        ['country' => 'Benin', 'country_code' => 'BJ', 'phone_code' => 'Benin BJ +229'],
        ['country' => 'Bhutan', 'country_code' => 'BT', 'phone_code' => 'Bhutan BT +975'],
        ['country' => 'Bolivia', 'country_code' => 'BO', 'phone_code' => 'Bolivia BO +591'],
        ['country' => 'Bosnia and Herzegovina', 'country_code' => 'BA', 'phone_code' => 'Bosnia and Herzegovina BA +387'],
        ['country' => 'Botswana', 'country_code' => 'BW', 'phone_code' => 'Botswana BW +267'],
        ['country' => 'Brazil', 'country_code' => 'BR', 'phone_code' => 'Brazil BR +55'],
        ['country' => 'Brunei', 'country_code' => 'BN', 'phone_code' => 'Brunei BN +673'],
        ['country' => 'Bulgaria', 'country_code' => 'BG', 'phone_code' => 'Bulgaria BG +359'],
        ['country' => 'Burkina Faso', 'country_code' => 'BF', 'phone_code' => 'Burkina Faso BF +226'],
        ['country' => 'Burundi', 'country_code' => 'BI', 'phone_code' => 'Burundi BI +257'],
        ['country' => 'Cambodia', 'country_code' => 'KH', 'phone_code' => 'Cambodia KH +855'],
        ['country' => 'Cameroon', 'country_code' => 'CM', 'phone_code' => 'Cameroon CM +237'],
        ['country' => 'Canada', 'country_code' => 'CA', 'phone_code' => 'Canada CA +1'],
        ['country' => 'Cape Verde', 'country_code' => 'CV', 'phone_code' => 'Cape Verde CV +238'],
        ['country' => 'Chile', 'country_code' => 'CL', 'phone_code' => 'Chile CL +56'],
        ['country' => 'China', 'country_code' => 'CN', 'phone_code' => 'China CN +86'],
        ['country' => 'Colombia', 'country_code' => 'CO', 'phone_code' => 'Colombia CO +57'],
        ['country' => 'Costa Rica', 'country_code' => 'CR', 'phone_code' => 'Costa Rica CR +506'],
        ['country' => 'Croatia', 'country_code' => 'HR', 'phone_code' => 'Croatia HR +385'],
        ['country' => 'Cuba', 'country_code' => 'CU', 'phone_code' => 'Cuba CU +53'],
        ['country' => 'Cyprus', 'country_code' => 'CY', 'phone_code' => 'Cyprus CY +357'],
        ['country' => 'Czech Republic', 'country_code' => 'CZ', 'phone_code' => 'Czech Republic CZ +420'],
        ['country' => 'Denmark', 'country_code' => 'DK', 'phone_code' => 'Denmark DK +45'],
        ['country' => 'Dominican Republic', 'country_code' => 'DO', 'phone_code' => 'Dominican Republic DO +1-809'],
        ['country' => 'Ecuador', 'country_code' => 'EC', 'phone_code' => 'Ecuador EC +593'],
        ['country' => 'Egypt', 'country_code' => 'EG', 'phone_code' => 'Egypt EG +20'],
        ['country' => 'El Salvador', 'country_code' => 'SV', 'phone_code' => 'El Salvador SV +503'],
        ['country' => 'Estonia', 'country_code' => 'EE', 'phone_code' => 'Estonia EE +372'],
        ['country' => 'Ethiopia', 'country_code' => 'ET', 'phone_code' => 'Ethiopia ET +251'],
        ['country' => 'Fiji', 'country_code' => 'FJ', 'phone_code' => 'Fiji FJ +679'],
        ['country' => 'Finland', 'country_code' => 'FI', 'phone_code' => 'Finland FI +358'],
        ['country' => 'France', 'country_code' => 'FR', 'phone_code' => 'France FR +33'],
        ['country' => 'Georgia', 'country_code' => 'GE', 'phone_code' => 'Georgia GE +995'],
        ['country' => 'Germany', 'country_code' => 'DE', 'phone_code' => 'Germany DE +49'],
        ['country' => 'Ghana', 'country_code' => 'GH', 'phone_code' => 'Ghana GH +233'],
        ['country' => 'Greece', 'country_code' => 'GR', 'phone_code' => 'Greece GR +30'],
        ['country' => 'Guatemala', 'country_code' => 'GT', 'phone_code' => 'Guatemala GT +502'],
        ['country' => 'Honduras', 'country_code' => 'HN', 'phone_code' => 'Honduras HN +504'],
        ['country' => 'Hong Kong', 'country_code' => 'HK', 'phone_code' => 'Hong Kong HK +852'],
        ['country' => 'Hungary', 'country_code' => 'HU', 'phone_code' => 'Hungary HU +36'],
        ['country' => 'Iceland', 'country_code' => 'IS', 'phone_code' => 'Iceland IS +354'],
        ['country' => 'India', 'country_code' => 'IN', 'phone_code' => 'India IN +91'],
        ['country' => 'Indonesia', 'country_code' => 'ID', 'phone_code' => 'Indonesia ID +62'],
        ['country' => 'Iran', 'country_code' => 'IR', 'phone_code' => 'Iran IR +98'],
        ['country' => 'Iraq', 'country_code' => 'IQ', 'phone_code' => 'Iraq IQ +964'],
        ['country' => 'Ireland', 'country_code' => 'IE', 'phone_code' => 'Ireland IE +353'],
        ['country' => 'Israel', 'country_code' => 'IL', 'phone_code' => 'Israel IL +972'],
        ['country' => 'Italy', 'country_code' => 'IT', 'phone_code' => 'Italy IT +39'],
        ['country' => 'Jamaica', 'country_code' => 'JM', 'phone_code' => 'Jamaica JM +1-876'],
        ['country' => 'Japan', 'country_code' => 'JP', 'phone_code' => 'Japan JP +81'],
        ['country' => 'Jordan', 'country_code' => 'JO', 'phone_code' => 'Jordan JO +962'],
        ['country' => 'Kazakhstan', 'country_code' => 'KZ', 'phone_code' => 'Kazakhstan KZ +7'],
        ['country' => 'Kenya', 'country_code' => 'KE', 'phone_code' => 'Kenya KE +254'],
        ['country' => 'Kuwait', 'country_code' => 'KW', 'phone_code' => 'Kuwait KW +965'],
        ['country' => 'Latvia', 'country_code' => 'LV', 'phone_code' => 'Latvia LV +371'],
        ['country' => 'Lebanon', 'country_code' => 'LB', 'phone_code' => 'Lebanon LB +961'],
        ['country' => 'Libya', 'country_code' => 'LY', 'phone_code' => 'Libya LY +218'],
        ['country' => 'Lithuania', 'country_code' => 'LT', 'phone_code' => 'Lithuania LT +370'],
        ['country' => 'Luxembourg', 'country_code' => 'LU', 'phone_code' => 'Luxembourg LU +352'],
        ['country' => 'Malaysia', 'country_code' => 'MY', 'phone_code' => 'Malaysia MY +60'],
        ['country' => 'Maldives', 'country_code' => 'MV', 'phone_code' => 'Maldives MV +960'],
        ['country' => 'Mali', 'country_code' => 'ML', 'phone_code' => 'Mali ML +223'],
        ['country' => 'Malta', 'country_code' => 'MT', 'phone_code' => 'Malta MT +356'],
        ['country' => 'Mauritius', 'country_code' => 'MU', 'phone_code' => 'Mauritius MU +230'],
        ['country' => 'Mexico', 'country_code' => 'MX', 'phone_code' => 'Mexico MX +52'],
        ['country' => 'Morocco', 'country_code' => 'MA', 'phone_code' => 'Morocco MA +212'],
        ['country' => 'Nepal', 'country_code' => 'NP', 'phone_code' => 'Nepal NP +977'],
        ['country' => 'Netherlands', 'country_code' => 'NL', 'phone_code' => 'Netherlands NL +31'],
        ['country' => 'New Zealand', 'country_code' => 'NZ', 'phone_code' => 'New Zealand NZ +64'],
        ['country' => 'Nigeria', 'country_code' => 'NG', 'phone_code' => 'Nigeria NG +234'],
        ['country' => 'Norway', 'country_code' => 'NO', 'phone_code' => 'Norway NO +47'],
        ['country' => 'Pakistan', 'country_code' => 'PK', 'phone_code' => 'Pakistan PK +92'],
        ['country' => 'Panama', 'country_code' => 'PA', 'phone_code' => 'Panama PA +507'],
        ['country' => 'Peru', 'country_code' => 'PE', 'phone_code' => 'Peru PE +51'],
        ['country' => 'Philippines', 'country_code' => 'PH', 'phone_code' => 'Philippines PH +63'],
        ['country' => 'Poland', 'country_code' => 'PL', 'phone_code' => 'Poland PL +48'],
        ['country' => 'Portugal', 'country_code' => 'PT', 'phone_code' => 'Portugal PT +351'],
        ['country' => 'Qatar', 'country_code' => 'QA', 'phone_code' => 'Qatar QA +974'],
        ['country' => 'Romania', 'country_code' => 'RO', 'phone_code' => 'Romania RO +40'],
        ['country' => 'Russia', 'country_code' => 'RU', 'phone_code' => 'Russia RU +7'],
        ['country' => 'Rwanda', 'country_code' => 'RW', 'phone_code' => 'Rwanda RW +250'],
        ['country' => 'Saudi Arabia', 'country_code' => 'SA', 'phone_code' => 'Saudi Arabia SA +966'],
        ['country' => 'Singapore', 'country_code' => 'SG', 'phone_code' => 'Singapore SG +65'],
        ['country' => 'South Africa', 'country_code' => 'ZA', 'phone_code' => 'South Africa ZA +27'],
        ['country' => 'South Korea', 'country_code' => 'KR', 'phone_code' => 'South Korea KR +82'],
        ['country' => 'Spain', 'country_code' => 'ES', 'phone_code' => 'Spain ES +34'],
        ['country' => 'Sri Lanka', 'country_code' => 'LK', 'phone_code' => 'Sri Lanka LK +94'],
        ['country' => 'Sweden', 'country_code' => 'SE', 'phone_code' => 'Sweden SE +46'],
        ['country' => 'Switzerland', 'country_code' => 'CH', 'phone_code' => 'Switzerland CH +41'],
        ['country' => 'Thailand', 'country_code' => 'TH', 'phone_code' => 'Thailand TH +66'],
        ['country' => 'Turkey', 'country_code' => 'TR', 'phone_code' => 'Turkey TR +90'],
        ['country' => 'Uganda', 'country_code' => 'UG', 'phone_code' => 'Uganda UG +256'],
        ['country' => 'Ukraine', 'country_code' => 'UA', 'phone_code' => 'Ukraine UA +380'],
        ['country' => 'United Arab Emirates', 'country_code' => 'AE', 'phone_code' => 'United Arab Emirates AE +971'],
        ['country' => 'United Kingdom', 'country_code' => 'GB', 'phone_code' => 'United Kingdom GB +44'],
        ['country' => 'United States', 'country_code' => 'US', 'phone_code' => 'United States US +1'],
        ['country' => 'Uruguay', 'country_code' => 'UY', 'phone_code' => 'Uruguay UY +598'],
        ['country' => 'Venezuela', 'country_code' => 'VE', 'phone_code' => 'Venezuela VE +58'],
        ['country' => 'Vietnam', 'country_code' => 'VN', 'phone_code' => 'Vietnam VN +84'],
        ['country' => 'Yemen', 'country_code' => 'YE', 'phone_code' => 'Yemen YE +967'],
        ['country' => 'Zimbabwe', 'country_code' => 'ZW', 'phone_code' => 'Zimbabwe ZW +263'],
    ]);
}

}
